- We are creating a very simple machine learning model.<br>
- Using dataset: tic-tac-toe.data.txt with user-defined columns.<br>
- We are treating this problem as a supervised learning problem.<br>

In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Imputer
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [2]:
# Loading data
data = pd.read_csv("../tic-tac-toe.data.txt", sep = ",")
data_copy = pd.read_csv("../tic-tac-toe.data.txt", sep = ",")

# Setting cols.
data.columns = ["first_row_left", "first_row_middle", "first_row_right", "center_row_left", "center_row_middle", "center_row_right", "bottom_row_left", "bottom_row_middle", "bottom_row_right", "is_win"]
data_copy.columns = ["first_row_left", "first_row_middle", "first_row_right", "center_row_left", "center_row_middle", "center_row_right", "bottom_row_left", "bottom_row_middle", "bottom_row_right", "is_win"]

In [3]:
# Viewing data
data.to_csv("data.csv")

In [4]:
# As we can see the the different move options, we perform label encoding.
mapping_for_moves = {'x':1, "o":0} # For b, we put mean of the data.
mapping_for_wins = {"positive":1, "negative":0} # Positive is win, negative is lose
data.is_win = data.is_win.map(mapping_for_wins)
data_copy.is_win = data_copy.is_win.map(mapping_for_wins)

data = data.drop(columns=["is_win"], axis=1)

In [5]:
data_copy.head()

first_row_left first_row_middle first_row_right center_row_left  \
0              x                x               x               x   
1              x                x               x               x   
2              x                x               x               x   
3              x                x               x               x   
4              x                x               x               x   

  center_row_middle center_row_right bottom_row_left bottom_row_middle  \
0                 o                o               o                 x   
1                 o                o               o                 o   
2                 o                o               o                 b   
3                 o                o               b                 o   
4                 o                o               b                 b   

  bottom_row_right  is_win  
0                o       1  
1                x       1  
2                b       1  
3                b       1  
4                o       1

In [6]:
for i in data.columns: # Applying map to all the columns except is_win.
    data[i] = data[i].map(mapping_for_moves)

In [7]:
# Extracting features and labels
features = data.values
labels = data_copy.is_win.values

In [8]:
# Filling missing values aka "b"
features = (Imputer().fit_transform(features))

In [9]:
len(features) 

957

In [10]:
len(labels)

957

In [11]:
# Changing type to int
features = features.astype(np.int)
labels = labels.astype(np.int)

In [12]:
features

array([[1, 1, 1, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 1, 0, 1],
       [0, 1, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 1, 1]])

In [13]:
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

- Preprocessing is done.

In [14]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, random_state=3, shuffle=True)

In [15]:
data.corr()

first_row_left  first_row_middle  first_row_right  \
first_row_left           1.000000         -0.050132        -0.141443   
first_row_middle        -0.050132          1.000000        -0.050132   
first_row_right         -0.141443         -0.050132         1.000000   
center_row_left         -0.050132         -0.259385        -0.343900   
center_row_middle       -0.126583         -0.137291        -0.126583   
center_row_right        -0.340581         -0.255754        -0.046933   
bottom_row_left         -0.141443         -0.343900        -0.043450   
bottom_row_middle       -0.340581          0.054459        -0.340581   
bottom_row_right        -0.040388         -0.340492        -0.138409   

                   center_row_left  center_row_middle  center_row_right  \
first_row_left           -0.050132          -0.126583         -0.340581   
first_row_middle         -0.259385          -0.137291         -0.255754   
first_row_right          -0.343900          -0.126583         -0.046933   
center_row_left           1.000000          -0.137291          0.054459   
center_row_middle        -0.137291           1.000000         -0.141296   
center_row_right          0.054459          -0.141296          1.000000   
bottom_row_left          -0.050132          -0.126583         -0.340581   
bottom_row_middle        -0.255754          -0.141296         -0.259962   
bottom_row_right         -0.340492          -0.130312         -0.050921   

                   bottom_row_left  bottom_row_middle  bottom_row_right  
first_row_left           -0.141443          -0.340581         -0.040388  
first_row_middle         -0.343900           0.054459         -0.340492  
first_row_right          -0.043450          -0.340581         -0.138409  
center_row_left          -0.050132          -0.255754         -0.340492  
center_row_middle        -0.126583          -0.141296         -0.130312  
center_row_right         -0.340581          -0.259962         -0.050921  
bottom_row_left           1.000000          -0.046933         -0.138409  
bottom_row_middle        -0.046933           1.000000         -0.050921  
bottom_row_right         -0.138409          -0.050921          1.000000

- Clearly it is a classification problem, we can use DecisionTree or SVC

In [16]:
# Trying different classifiers.
clf = DecisionTreeClassifier()
clf.fit(features_train, labels_train)
d_tree_score = clf.score(features_test, labels_test) # Good result!

In [17]:
clf2 = SVC() # Clearly the data is non linear.
clf2.fit(features_train, labels_train)
clf2.score(features_test, labels_test) # Not good!

0.8583333333333333

In [18]:
clf3 = KNeighborsClassifier(n_neighbors=1)
clf3.fit(features_train, labels_train)
k_score = clf3.score(features_test, labels_test)

In [19]:
d_tree_score > k_score

False

In [20]:
predictions = clf3.predict(features_test)

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, predictions)

In [22]:
cm

array([[ 78,   3],
       [  2, 157]])

In [23]:
np.where(labels_test!=predictions)

(array([ 17,  74, 178, 212, 219]),)

In [24]:
d_tree_score


0.9791666666666666

In [25]:
k_score

0.9791666666666666

In [26]:
from sklearn.metrics import classification_report
c = classification_report(labels_test, predictions)

In [27]:
c

'             precision    recall  f1-score   support\n\n          0       0.97      0.96      0.97        81\n          1       0.98      0.99      0.98       159\n\navg / total       0.98      0.98      0.98       240\n'

In [28]:
from sklearn.ensemble import RandomForestClassifier
r = RandomForestClassifier(n_estimators=100) # With 100 decision tree
r.fit(features_train, labels_train)
r_forest = r.score(features_test, labels_test)
p = r.predict(features_test)
np.where(labels_test!=features_test) # Only one misclassified
r_forest

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:6: DeprecationWarning: elementwise != comparison failed; this will raise an error in the future.
  


0.9833333333333333

In [29]:
cm  = confusion_matrix(labels_test, p)

In [30]:
cm

array([[ 79,   2],
       [  2, 157]])

In [31]:
from sklearn.externals import joblib

In [32]:
from sklearn.model_selection import GridSearchCV


In [33]:
param = [ {"n_estimators":[10,100 ,1000]}]
r = RandomForestClassifier()
clf = GridSearchCV(r, param)
clf.fit(features_train, labels_train)

GridSearchCV(cv=None, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'n_estimators': [10, 100, 1000]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [34]:
clf.best_score_

0.9748953974895398

In [35]:
data_copy.head()

first_row_left first_row_middle first_row_right center_row_left  \
0              x                x               x               x   
1              x                x               x               x   
2              x                x               x               x   
3              x                x               x               x   
4              x                x               x               x   

  center_row_middle center_row_right bottom_row_left bottom_row_middle  \
0                 o                o               o                 x   
1                 o                o               o                 o   
2                 o                o               o                 b   
3                 o                o               b                 o   
4                 o                o               b                 b   

  bottom_row_right  is_win  
0                o       1  
1                x       1  
2                b       1  
3                b       1  
4                o       1

In [36]:
import coremltools


In [43]:
coremltools.converters.sklearn.convert(clf, ,output_feature_names="is_win",input_features=["first_row_left","first_row_middle", "first_row_right", "center_row_left", "center_row_middle", "center_row_right", "bottom_row_left", "bottom_row_middle", "bottom_row_right"])

SyntaxError: invalid syntax (<ipython-input-43-b320d5dc12fe>, line 1)

In [46]:
import keras
from keras.layers import Dense
from keras import Sequential
model = Sequential()
model.add(Dense(100, input_dim=features_train.shape[1], activation="tanh"))
model.add(Dense(100, activation="relu"))
model.add(Dense(1, activation="softmax"))

model.compile(optimizer="adam", loss=keras.losses.binary_crossentropy, metrics=["accuracy"])
model.fit(features_train, labels_train, epochs=50)

Epoch 1/50
717/717 [==============================] - 0s 428us/step - loss: 5.5809 - acc: 0.6499
Epoch 2/50
717/717 [==============================] - 0s 79us/step - loss: 5.5809 - acc: 0.6499
Epoch 3/50
717/717 [==============================] - 0s 82us/step - loss: 5.5809 - acc: 0.6499
Epoch 4/50
717/717 [==============================] - 0s 81us/step - loss: 5.5809 - acc: 0.6499
Epoch 5/50
717/717 [==============================] - 0s 82us/step - loss: 5.5809 - acc: 0.6499
Epoch 6/50
717/717 [==============================] - 0s 92us/step - loss: 5.5809 - acc: 0.6499
Epoch 7/50
717/717 [==============================] - 0s 99us/step - loss: 5.5809 - acc: 0.6499
Epoch 8/50
717/717 [==============================] - 0s 94us/step - loss: 5.5809 - acc: 0.6499
Epoch 9/50
717/717 [==============================] - 0s 93us/step - loss: 5.5809 - acc: 0.6499
Epoch 10/50
717/717 [==============================] - 0s 83us/step - loss: 5.5809 - acc: 0.6499
Epoch 11/50
717/717 [=================